### ISSUE TITLE
Numpy Version Requires to be <= 1.23.5

### ISSUE THREAD

**Issue by LandonSwartz** [meyerls/pc-skeletor#13] opened 2023-07-14 15:48 UTC
For lbc.extract_topology(), there is a use of np.bool that does not execute if the numpy version is over 1.23.5. The np.bool value is deprecated after 1.20 and not able to be used after 1.23.5. Great work though.

**Comment by meyerls** [comment] 2023-07-15 09:32
Hi @LandonSwartz,

I assume the error is caused by the package [mistree](https://github.com/knaidoo29/mistree). To fix the error I have created a [pull request](https://github.com/knaidoo29/mistree/pull/20) but it has not been merged yet. 

A current fix can be found on my forked version: the [https://github.com/meyerls/mistree](https://github.com/meyerls/mistree). Just install mistree from source and the error should be gone.  

Did it work out?

**Closed by meyerls** 2023-07-15 09:32 UTC

**Comment by LandonSwartz** [comment] 2023-07-17 14:54
Yes it did work out, I just uninstall mistree and set the numpy version to <= 1.23.5 and reinstalled. Works great! Very hopeful you can implement the L1 medial skeleton. I have tried and failed many times to do it in python.

**Comment by SamBum92** [comment] 2023-08-29 15:12
This repo [https://github.com/meyerls/mistree](https://github.com/meyerls/mistree) is mistree 1.2.1
This one [https://github.com/knaidoo29/mistree](https://github.com/knaidoo29/mistree) is mistree 1.2.2
When install, pip inform that actual [pc-skeletor](https://github.com/meyerls/pc-skeletor) (1.0.0) is in conflict with these versions:
_ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pc-skeletor 1.0.0 requires mistree==1.2.0, but you have mistree 1.2.1 which is incompatible._
but it seems to work

**Comment by EGuney-1** [comment] 2024-06-04 14:16
This did not solve the issue for me, am still getting the following error message when pip is installing mistree: `ModuleNotFoundError: No module named 'numpy'`.

I have tried this both on Windows 11 and Ubuntu 20.04.4 LTS. I have tried it with Python versions 3.10, 3.11 and 3.12 and made sure to install NumPy with version `<=1.23.5` first. I have tried all these by manually cloning mistree, both with the current version `1.2.2` and with the version `1.2.1` that was forked. 

Do you have any ideas what else the cause of this may be?

**Comment by meyerls** [comment] 2024-06-04 14:56
What is your specific error? Have you tried reinstalling numpy? Did you install my version of mistree?

**Comment by EGuney-1** [comment] 2024-06-04 15:21
Thanks for the swift response, yes I have started over from a clean venv a couple times, made sure to install the aforementioned NumPy version and also tried [your fork of mistree](https://github.com/meyerls/mistree). I always end up with the same error below:

![image](https://github.com/meyerls/pc-skeletor/assets/146717372/9b849c44-c3f7-4908-93ee-7eb5482acdd4)

(It is clear that this issue is related to mistree and not this repository, but I've seen someone else raise the same issue but the author of mistree just said he doesn't know and left it at that :/. So I don't want to take much of your time, let me know if potential solutions come to mind, if not I'll have to look for alternatives. Thanks in advance.)
